### PR TITLE
chore: improve icons gallery grid

### PR DESCRIPTION
**Pull request by paulgrym**
## Jira issue

JIRA issue: [FSU-74](https://klau.atlassian.net/browse/FSU-74)

## Describe your changes
I changed gallery display to grid and adjust the rest of styles to this new "grid" situation :) .  
I also removed the div added on FSU-33, because it changed the position of the icon name (previously the name was under the icon, and adding the div made it next to the icon).

## Checklist before requesting a review

- [x] Checked which branch you would merge.
- [x] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [x] Performed a self-review of code (bugs, clean code rules, etc).
- [x] Checked if added variables have unique names.
- [x] Checked if added code/function is not a duplicate. 
- [x] Tests have been added if possible.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by nata-kab — CHANGES_REQUESTED** [review]
Looks great.😍 🚀 
There is only one thing left. After the changes, "Theme" disappeared from the Storybook gallery. 🕵️‍♀️

**Comment by paulgrym** [comment]
> 

There is no Theme in Storybook on main so I don't think my changes made it disappear 🙃 Maybe FSU-67?

**Comment by nata-kab** [comment]
> @nata-kab there is no Theme in Storybook on main so I don't think my changes made it disappear 🙃 Maybe FSU-67? I'm creating a new task for that fix ;) 

It's weird.🤔 I can see "Theme" in the Storybook gallery on the main branch.

**Comment by nata-kab** [comment]
Screenshot 2022-10-28 at 10 51 27

**Review by nata-kab — APPROVED** [review]
🚀

**Comment by paulgrym** [comment]
You need to pull recent changes to main

**Comment by nata-kab** [comment]
I saw your branch 😅 
There is no way the Theme gallery would run after the theme file has been moved. It worked on my main because I did git fetch and then checkout witch usually works. 🙈 I hadn't recent changes on my local main.
I'm glad that you fixed Theme import issue 🙌

**Review by im-klau — APPROVED** [review]
what a beautiful improvement! thank you 😍

**Pull request merged**
