### PR TITLE
feat(adoption): update hero background

### PR DESCRIPTION
**Pull request by im-klau**
## Jira issue

JIRA issue: [FSU-253](https://klau.atlassian.net/browse/FSU-253)

## Describe your changes
This PR updates the Adoption's hero image to the new one. It also adjusts styles a little bit to fit the new image.

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by AmandaKr — COMMENTED** [review]
perfect 🚀

**Review by AmandaKr — COMMENTED** [review]
perfect 🚀

**Review by AmandaKr — APPROVED** [review]
perfect 🚀

**Review by Ebmili — APPROVED** [review]
Well done :)

**Pull request merged**
