### PR TITLE
build: theme

### PR DESCRIPTION
**Pull request by AmandaKr**
## build:  FSU-67 move theme

build: move the theme folder outside of the components directory

## Jira issue

JIRA issue: [FSU-67](https://klau.atlassian.net/browse/FSU-67)

## Describe your changes
I moved theme component outside the components directory to keep the structure a little bit cleaner 💦

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by im-klau** [comment]
It looks like this PR creates new `theme` directory, but there aren't any changes in Github related to deleting the old theme file 🤔

**Comment by AmandaKr** [comment]
I didn't notice that theme was duplicated, my mistake, corrected 👍

**Comment by AmandaKr** [comment]
what happened here? : o

**Review by im-klau — APPROVED** [review]

**Review by nata-kab — APPROVED** [review]
🚀

**Pull request merged**
