### PR TITLE
feat: add favicon

### PR DESCRIPTION
**Pull request by paulgrym**
## Jira issue

JIRA issue: [FSU-244](https://klau.atlassian.net/browse/FSU-244)

## Describe your changes
Add favicons to the website

## Checklist before requesting a review

- [x] Checked which branch you would merge.
- [x] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [x] Performed a self-review of code (bugs, clean code rules, etc).
- [x] Checked if added variables have unique names.
- [x] Checked if added code/function is not a duplicate. 
- [x] Tests have been added if possible.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by nata-kab — APPROVED** [review]
Love this cute icon 😍 👍
[Uploading Screenshot 2023-05-19 at 16.20.42.png…]()

**Review by AmandaKr — APPROVED** [review]
😻

**Review by Ebmili — APPROVED** [review]
Well done :)

**Review by Ebmili — APPROVED** [review]
Well done :)

**Review by im-klau — APPROVED** [review]

**Pull request merged**
