### PR TITLE
feat: feature update

### PR DESCRIPTION
**Pull request by AmandaKr**
## Jira issue

JIRA issue: [FSU-241](https://klau.atlassian.net/browse/FSU-241)

## Describe your changes

This PR introduces new layout for Feature component on mobile.

## Checklist before requesting a review

- [x] Checked which branch you would merge.
- [x] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [x] Performed a self-review of code (bugs, clean code rules, etc).
- [x] Checked if added variables have unique names.
- [x] Checked if added code/function is not a duplicate. 
- [x] Tests have been added if possible.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by paulgrym — APPROVED** [review]
Great! ⭐

**Review by nata-kab — COMMENTED** [review]
Great job, just one more thing. 😀
Please, mark description as required (is in Figma component description). 😉

**Review by nata-kab — APPROVED** [review]
🚀

**Review by im-klau — APPROVED** [review]
quick fix 🎉

**Pull request merged**
