### PR TITLE
feat: card v2

### PR DESCRIPTION
**Pull request by im-klau**
## Jira issue

JIRA issue: [FSU-266](https://klau.atlassian.net/browse/FSU-266)

## Describe your changes
This PR introduces a simplified version of our Card component.
It also updates all cards used in our project.

## Checklist before requesting a review

- [x] Checked which branch you would merge.
- [x] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [x] Performed a self-review of code (bugs, clean code rules, etc).
- [x] Checked if added variables have unique names.
- [x] Checked if added code/function is not a duplicate. 
- [x] Tests have been added if possible.
- [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by AmandaKr — COMMENTED** [review]
image
Button is too close to List, also on mobile

**Review by paulgrym — APPROVED** [review]
Excellent ✨

**Review by AmandaKr — APPROVED** [review]
🚀

**Review by AmandaKr — APPROVED** [review]
🚀

**Pull request merged**
