### PR TITLE
feat: introduce basic file and folder names linting

### PR DESCRIPTION
**Pull request by im-klau**
## Jira issue

JIRA issue: [FSU-70](https://klau.atlassian.net/browse/FSU-70)

## Describe your changes
This PR introduces an additional eslint plugin that checks if our folder and file use the proper casing.
Current naming convention rules:
- folder name should use `camelCase`
- component file name should use `camelCase`

## Checklist before requesting a review

- [ ] Checked which branch you would merge.
- [ ] Checked if the code follows the style guidelines of this project (use eslint and prettier).
- [ ] Performed a self-review of code (bugs, clean code rules, etc).
- [ ] Checked if added variables have unique names.
- [ ] Checked if added code/function is not a duplicate. 
- [ ] Tests have been added if possible.
- [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by nata-kab — APPROVED** [review]
I checked and it works 😉 🙌
Screenshot 2022-12-14 at 12 22 34

**Comment by im-klau** [comment]
> I checked and it works 😉 🙌 Screenshot 2022-12-14 at 12 22 34

Could you maybe run `yarn install` and double-check it still works? 🙏

**Review by AmandaKr — APPROVED** [review]
I changed name of textBanner to textbanner and yarn lint didm't pass, so it works fine 🚀 
image

**Comment by AmandaKr** [comment]
> > I checked and it works 😉 🙌 Screenshot 2022-12-14 at 12 22 34
> 
> Could you maybe run `yarn install` and double-check it still works? 🙏

Yup, @nata-kab you should first run yarn install and then try to change folders or components name

**Pull request merged**
